import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Header from "../components/header";
import Footer from "../components/footer";
import Container from "react-bootstrap/esm/Container";
import { Bounce, ToastContainer } from 'react-toastify';
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css"; // file css chung toàn site


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={`${geistSans.variable} ${geistMono.variable} antialiased d-flex flex-column min-vh-100`}>
        <Header />
        <main className="flex-grow-1">
          <Container>{children}</Container>
        </main>
          <ToastContainer
            position="top-center"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
        <Footer />
      </body>
    </html>
  );
}
